server:
  port: 8900

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: ARoutes
          uri: http://localhost:8082
          predicates:     #断言（匹配条件）
            - Path=/ta/**    #用户访问http://localhost:8900/ta/method1时，用户实际访问路径为localhost:8082/ta/method1
      default-filters:    #路由的默认过滤器
        - StripPrefix=1    #去掉前置路径数，此时的实际访问路径为http://localhost:8900/method1