server:
  port: 8080
  servlet:
    context-path: /user_sys

spring:
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

logging:
  level:
    com.etoak.mapper: debug

resilience4j:
  circuitbreaker:
    instances:
      backendA:
        registerHealthIndicator: true
        slidingWindowSize: 100
