server:
  port: 8084

spring:
  application:
    name: config-server
  cloud:
    consul:
      host: localhost
      port: 8500
    config:
      server:
        git:
          uri: http://gitlab.huayao.com:11080/dengli/config-repo.git
          default-label: main
  rabbitmq:
    host: localhost
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "*"